## This configuration was generated by terraform-provider-oci



resource oci_functions_application export_DataSyncApplication {
  compartment_id = var.compartment_ocid
  config = {
    "_400_error_stream_ocid"    = oci_streaming_stream.export_UnrecoverableErrorStream.id
    "_404_error_stream_ocid"    = oci_streaming_stream.export_UnrecoverableErrorStream.id
    "_503_error_stream_ocid"    = oci_streaming_stream.export_ServerUnavailableStream.id
    "default_error_stream_ocid" = oci_streaming_stream.export_ServerUnavailableStream.id
    "vault_compartment_ocid"    = var.compartment_ocid
    "vault_key_ocid"            = oci_kms_key_version.export_SyncDataEncryptionKey_key_version_1.id
    "vault_ocid"                = oci_kms_vault.export_DataSync_Vault.id
  }
 
  display_name = "DataSyncApplication"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  subnet_ids = [
    oci_core_subnet.export_Public-Subnet-DataSyncVCN.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}





