## This configuration was generated by terraform-provider-oci

resource oci_kms_vault export_DataSync_Vault {
  compartment_id = var.compartment_ocid
 
  display_name = "DataSync_Vault"
 
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
  vault_type = "DEFAULT"
}

resource oci_kms_key export_SyncDataEncryptionKey {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  desired_state = "ENABLED"
  display_name  = "SyncDataEncryptionKey"
  freeform_tags = {
  }
  key_shape {
    algorithm = "AES"
    curve_id  = ""
    length    = "32"
  }
  management_endpoint = var.key_management_endpoint
  protection_mode     = "HSM"
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
}

resource oci_kms_key_version export_SyncDataEncryptionKey_key_version_1 {
  key_id              = oci_kms_key.export_SyncDataEncryptionKey.id
  management_endpoint = var.key_management_endpoint
  #time_of_deletion = <<Optional value not found in discovery>>
}

