## This configuration was generated by terraform-provider-oci

resource oci_sch_service_connector export_ServerUnavailableToNotificationsConnector {
  
  compartment_id = var.compartment_ocid
  
  #description = <<Optional value not found in discovery>>
  display_name = "ServerUnavailableToNotificationsConnector"
  freeform_tags = {
  }
  source {
    cursor {
      kind = "LATEST"
    }
    kind = "streaming"
    #log_sources = <<Optional value not found in discovery>>
    stream_id = oci_streaming_stream.export_ServerUnavailableStream.id
  }
  state = "ACTIVE"
  target {
    #batch_rollover_size_in_mbs = <<Optional value not found in discovery>>
    #batch_rollover_time_in_ms = <<Optional value not found in discovery>>
    #bucket = <<Optional value not found in discovery>>
    #compartment_id = <<Optional value not found in discovery>>
    #dimensions = <<Optional value not found in discovery>>
    enable_formatted_messaging = "false"
    #function_id = <<Optional value not found in discovery>>
    kind = "notifications"
    #log_group_id = <<Optional value not found in discovery>>
    #metric = <<Optional value not found in discovery>>
    #metric_namespace = <<Optional value not found in discovery>>
    #namespace = <<Optional value not found in discovery>>
    #object_name_prefix = <<Optional value not found in discovery>>
    #stream_id = <<Optional value not found in discovery>>
    topic_id = oci_ons_notification_topic.export_ErrorTopic.id
  }
}

resource oci_sch_service_connector export_UnrecoverableErrorToNotificationsConnector {
  compartment_id = var.compartment_ocid
 
  description  = "UnrecoverableErrorToNotificationsConnector"
  display_name = "UnrecoverableErrorToNotificationsConnector"
  freeform_tags = {
  }
  source {
    cursor {
      kind = "LATEST"
    }
    kind = "streaming"
    #log_sources = <<Optional value not found in discovery>>
    stream_id = oci_streaming_stream.export_UnrecoverableErrorStream.id
  }
  state = "ACTIVE"
  target {
    #batch_rollover_size_in_mbs = <<Optional value not found in discovery>>
    #batch_rollover_time_in_ms = <<Optional value not found in discovery>>
    #bucket = <<Optional value not found in discovery>>
    #compartment_id = <<Optional value not found in discovery>>
    #dimensions = <<Optional value not found in discovery>>
    enable_formatted_messaging = "false"
    #function_id = <<Optional value not found in discovery>>
    kind = "notifications"
    #log_group_id = <<Optional value not found in discovery>>
    #metric = <<Optional value not found in discovery>>
    #metric_namespace = <<Optional value not found in discovery>>
    #namespace = <<Optional value not found in discovery>>
    #object_name_prefix = <<Optional value not found in discovery>>
    #stream_id = <<Optional value not found in discovery>>
    topic_id = oci_ons_notification_topic.export_ErrorTopic.id
  }
}

resource oci_sch_service_connector export_UnrecoverableErrorToStorageConnector {
  compartment_id = var.compartment_ocid
  
  description  = "UnrecoverableErrorToStorageConnector"
  display_name = "UnrecoverableErrorToStorageConnector"
  freeform_tags = {
  }
  source {
    cursor {
      kind = "LATEST"
    }
    kind = "streaming"
    #log_sources = <<Optional value not found in discovery>>
    stream_id = oci_streaming_stream.export_UnrecoverableErrorStream.id
  }
  state = "ACTIVE"
  target {
    batch_rollover_size_in_mbs = "100"
    batch_rollover_time_in_ms  = "420000"
    bucket                     = "stream-error-bucket"
    #compartment_id = <<Optional value not found in discovery>>
    #dimensions = <<Optional value not found in discovery>>
    #enable_formatted_messaging = <<Optional value not found in discovery>>
    #function_id = <<Optional value not found in discovery>>
    kind = "objectStorage"
    #log_group_id = <<Optional value not found in discovery>>
    #metric = <<Optional value not found in discovery>>
    #metric_namespace = <<Optional value not found in discovery>>
    #namespace = <<Optional value not found in discovery>>
    #object_name_prefix = <<Optional value not found in discovery>>
    #stream_id = <<Optional value not found in discovery>>
    #topic_id = <<Optional value not found in discovery>>
  }
}

resource oci_sch_service_connector export_DataSyncServiceConnector {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  description  = "DataSyncServiceConnector"
  display_name = "DataSyncServiceConnector"
  freeform_tags = {
  }
  source {
    cursor {
      kind = "LATEST"
    }
    kind = "streaming"
    #log_sources = <<Optional value not found in discovery>>
    stream_id = oci_streaming_stream.export_DataSyncStream.id
  }
  state = "ACTIVE"
  target {
    #batch_rollover_size_in_mbs = <<Optional value not found in discovery>>
    #batch_rollover_time_in_ms = <<Optional value not found in discovery>>
    #bucket = <<Optional value not found in discovery>>
    #compartment_id = <<Optional value not found in discovery>>
    #dimensions = <<Optional value not found in discovery>>
    #enable_formatted_messaging = <<Optional value not found in discovery>>
    function_id = data.oci_functions_functions.test_deploy_ReadDataStreamFunction.functions[0].id
    kind        = "functions"
    #log_group_id = <<Optional value not found in discovery>>
    #metric = <<Optional value not found in discovery>>
    #metric_namespace = <<Optional value not found in discovery>>
    #namespace = <<Optional value not found in discovery>>
    #object_name_prefix = <<Optional value not found in discovery>>
    #stream_id = <<Optional value not found in discovery>>
    #topic_id = <<Optional value not found in discovery>>
  }
}

