## This configuration was generated by terraform-provider-oci

resource oci_streaming_stream_pool export_DefaultPool {
  compartment_id = var.compartment_ocid
  custom_encryption_key {
    kms_key_id = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  }
  defined_tags = {
  }
  freeform_tags = {
  }
  kafka_settings {
    auto_create_topics_enable = "false"
    log_retention_hours       = "24"
    num_partitions            = "1"
  }
  name = "DefaultPool"
  private_endpoint_settings {
    nsg_ids = [
    ]
    #private_endpoint_ip = <<Optional value not found in discovery>>
    #subnet_id = <<Optional value not found in discovery>>
  }

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [custom_encryption_key[0].kms_key_id]
  }
}

resource oci_streaming_stream export_ServerUnavailableStream {
  compartment_id = var.compartment_ocid
 
  freeform_tags = {
  }
  name               = "ServerUnavailableStream"
  partitions         = "1"
  retention_in_hours = "24"
  #stream_pool_id = <<Optional value not found in discovery>>
}

resource oci_streaming_stream export_UnrecoverableErrorStream {
  compartment_id = var.compartment_ocid
  
  freeform_tags = {
  }
  name               = "UnrecoverableErrorStream"
  partitions         = "1"
  retention_in_hours = "24"
  #stream_pool_id = <<Optional value not found in discovery>>
}

resource oci_streaming_stream export_DataSyncStream {
  compartment_id = var.compartment_ocid
 
  freeform_tags = {
  }
  name               = "DataSyncStream"
  partitions         = "1"
  retention_in_hours = "24"
  #stream_pool_id = <<Optional value not found in discovery>>
}

